fix: metrics consent prompt location and styling
ipfs/public-gateway-checker pull request #353
Opened 2022-12-20 01:26 UTC by djmcquillan

Fixes #341 and addresses #340 

- Moved cookie toggle button to lower left
- Updated metric consent prompt to be fixed at bottom of page
- Updated styles of metric consent prompt (interim fix until new modal updates are added in #340)
<img width="1273" alt="Screen Shot 2022-12-19 at 2 02 47 PM" src="https://user-images.githubusercontent.com/10619673/208559560-1c6b543c-feb8-48df-b9b2-6b1e698893bf.png">

https://user-images.githubusercontent.com/10619673/208559656-0ffbd34a-c5d3-4ed4-82bf-149696d4ba54.mov

2022-12-20 02:38 UTC, SgtPooki requested changes

2022-12-20 02:38 UTC, SgtPooki commented on src/index.html
> +  <div class="hidden js-metrics-notification metrics-notification-wrapper bg-navy bt bw1 border-aqua">
move to bottom of body

2022-12-20 02:38 UTC, SgtPooki commented on src/styles.css
> +  left: 15px;
we should move the HTML for this toggle appropriately as well (to bottom of body)

2022-12-20 02:40 UTC, SgtPooki commented
we should make sure that the banner changes aren't doing new breakages on mobile, but not about fixing any existing issues in this PR (we should open issues for them to address later)

2022-12-21 02:16 UTC, djmcquillan commented
> I'm seeing a bunch of weird behaviours on smaller screens

@whizzzkid I have updated the styling to address the issues you pointed out.

2023-01-03 19:46 UTC, djmcquillan commented on src/styles.css
> +  z-index: 1;
I would have thought so too! it should have, but firefox was having issue with scroll as you noticed so the results table container needed an overflow setting

2023-01-04 17:16 UTC, SgtPooki approved these changes

2023-01-04 20:27 UTC, merged