fix: 340 - updates to metrics collection to use modal ux
ipfs/public-gateway-checker pull request #359
Opened 2023-01-07 03:12 UTC by djmcquillan

fixes: #340

- updated metrics collection to use modal designs laid out in #340 and discussions occurring in multiple areas but consolidated here

https://user-images.githubusercontent.com/10619673/211126809-8d51d796-4121-4dc3-a2a0-ec417d7e4b1c.mov

2023-01-10 23:34 UTC, SgtPooki requested changes

2023-01-10 23:34 UTC, SgtPooki commented on src/index.html
>  <!DOCTYPE html>
https://github.com/ipfs/public-gateway-checker/pull/366

2023-01-10 23:34 UTC, SgtPooki commented on src/styles.css
> +body,
see https://github.com/ipfs/public-gateway-checker/pull/366.

2023-01-10 23:47 UTC, SgtPooki commented
Testing the changes on the [preview build](https://bafybeidjcdcqe4yvke2j4qlcepomkwopjf2h3lihkfeflefuixdhj2m4vm.on.fleek.co/) look good except for one thing:

Metrics are disabled upon page load:

![image](https://user-images.githubusercontent.com/1173416/211685092-c1ec029a-64e0-44e9-bb13-cbf37a1aa959.png)

we could probably address this issue and a few of my comments on this PR in another issue, https://github.com/ipfs/public-gateway-checker/issues/367

2023-01-16 23:31 UTC, closed without merging

2023-01-18 01:02 UTC, tinytb commented
Replaced by https://github.com/ipfs/public-gateway-checker/pull/373