Fix/metrics toggle modal/340
ipfs/public-gateway-checker pull request #373
Opened 2023-01-16 23:25 UTC by djmcquillan

fixes: #340 

Updated PR for #340 adding modal and toggles for metrics collection

https://user-images.githubusercontent.com/10619673/212779585-fd8b5e3b-2614-4136-814d-437f7d12de7a.mov

2023-01-17 04:47 UTC, SgtPooki approved these changes

2023-01-17 21:38 UTC, juliaxbow commented
Not blockers but some comments included in the screenshots below. Also there's an open question in the ignite channel about whether the metrics policy should link out [to the github isse
](https://github.com/ipfs/ipfs-gui/issues/125) or the [companion privacy policy ](https://github.com/ipfs/ipfs-companion/blob/main/PRIVACY-POLICY.md). I believe the last decision was to move towards the former while we wait on a broader-reaching policy from Legal. 

### Desktop
#### Current
<img width="177" alt="Screen Shot 2023-01-17 at 1 29 55 PM" src="https://user-images.githubusercontent.com/58958327/213016584-277008c3-ce57-40f2-bdd1-d30fadafc50d.png">

#### With suggested changes
<img width="429" alt="Screen Shot 2023-01-17 at 1 33 05 PM" src="https://user-images.githubusercontent.com/58958327/213016988-c355b733-95da-416c-a5f8-78d662a2aae8.png">

### Mobile:
<img width="296" alt="Screen Shot 2023-01-17 at 1 35 22 PM" src="https://user-images.githubusercontent.com/58958327/213017377-4cbd1efe-60ef-4404-8a35-ab8fec751cc8.png">

2023-01-17 22:27 UTC, SgtPooki requested changes

2023-01-17 22:27 UTC, SgtPooki commented on src/metrics.ts
> +    addConsent(['all'])
this should be addConsent(['minimal']) shouldn't it

2023-01-17 22:29 UTC, SgtPooki commented
> Also there's an open question in the ignite channel about whether the metrics policy should link out https://github.com/ipfs/ipfs-gui/issues/125
or the [companion privacy policy ](https://github.com/ipfs/ipfs-companion/blob/main/PRIVACY-POLICY.md). I believe the last decision was to move towards the former while we wait on a broader-reaching policy from Legal.

We should link to https://github.com/ipfs-shipyard/ignite-metrics/blob/main/docs/telemetry/COLLECTION_POLICY.md

2023-01-17 22:29 UTC, SgtPooki commented on src/index.html
> +            For more details, read the full<a href="https://github.com/ipfs/ipfs-gui/issues/125"> metrics collection policy</a>.
we should link to https://github.com/ipfs-shipyard/ignite-metrics/blob/main/docs/telemetry/COLLECTION_POLICY.md

```suggestion
            For more details, read the full<a href="https://github.com/ipfs-shipyard/ignite-metrics/blob/main/docs/telemetry/COLLECTION_POLICY.md"> metrics collection policy</a>.
```

2023-01-18 05:18 UTC, SgtPooki approved these changes
Lgtm, lets get this shipped

2023-01-18 17:53 UTC, merged