feat: add storage.web3ph.dev
ipfs/public-gateway-checker pull request #435
Opened 2023-07-26 10:35 UTC by alvin-reyes

This is a dedicated gateway from web3ph group from Philippines. 

The server is located in Singapore.

2023-07-26 10:37 UTC, warengonzaga commented
Let's goooo, thanks @alvin-reyes for the PR. We are excited to see our public gateway live to list!

2023-07-28 18:45 UTC, SgtPooki requested changes

2023-07-28 18:45 UTC, SgtPooki commented on src/gateways.ts
> +  'https://storage.web3ph.dev/gw/:hash'
trailing comma is required as it will prevent rebase hell
```suggestion
  'https://storage.web3ph.dev/gw/:hash',
```

2023-07-28 18:47 UTC, SgtPooki approved these changes
it's online but isn't passing many tests: 

![image](https://github.com/ipfs/public-gateway-checker/assets/1173416/de9f353f-5591-43a3-af55-67bb3430bd00)

2023-07-28 18:56 UTC, merged