feat: twdragon.net
ipfs/public-gateway-checker pull request #444
Opened 2023-08-07 16:17 UTC by twdragon

Added twdragon.net to the list of public gateways.

**NOTE**: The gateway supports only subdomain addressing, the case-sensitive path-based CID addressing is blocked programmatically.

2023-08-08 20:32 UTC, SgtPooki requested changes

2023-08-08 20:32 UTC, SgtPooki commented on src/gateways.ts
> +  'https://ipfs.twdragon.net/ipfs/:hash'
```suggestion
  'https://ipfs.twdragon.net/ipfs/:hash',
```
@twdragon we need trailing commas now. I should probably add a pre-commit hook to this repo.

2023-08-10 09:36 UTC, twdragon commented
@SgtPooki as now everything looks fine, may we proceed, or do you want me to reopen the PR?

2023-08-11 18:16 UTC, SgtPooki commented
Sorry i got pulled away previously. Gimme one sec

2023-08-11 18:20 UTC, SgtPooki commented
@twdragon it looks like it's failing all checks at this point? 

![image](https://github.com/ipfs/public-gateway-checker/assets/1173416/d3925688-9b30-4e7a-be5d-56d17b1ab6c3)

2023-08-18 16:03 UTC, twdragon commented
@SgtPooki I disabled path-based CID resolving at all at the gateway, so URIs like `/ipfs/CID` are leading to 403 response. Is it a problem?

2023-08-22 20:31 UTC, SgtPooki commented
@twdragon it should be fine as we have one check that uses subdomain checks, but your gateway is failing even that check.

We're checking the following URLs and all of them are failing using twdragon.net:

* https://ipfs.twdragon.net/ipfs/bafybeifx7yeb55armcsxwwitkymga5xf53dxiarykms3ygqic223w5sk3m?now=1692736124371
* https://ipfs.twdragon.net/ipns/en.wikipedia-on-ipfs.org/favicon.ico?now=1692736124371
* https://ipfs.twdragon.net/ipfs/bafybeifx7yeb55armcsxwwitkymga5xf53dxiarykms3ygqic223w5sk3m?format=raw&now=1692736124372
* https://ipfs.twdragon.net/ipfs/bafybeifx7yeb55armcsxwwitkymga5xf53dxiarykms3ygqic223w5sk3m?format=car&now=1692736124372
* https://ipfs.twdragon.net/ipfs/bafybeibwzifw52ttrkqlikfzext5akxu7lz4xiwjgwzmqcpdzmp3n5vnbe?now=1692736124371&filename=1x1.png
* https://bafybeibwzifw52ttrkqlikfzext5akxu7lz4xiwjgwzmqcpdzmp3n5vnbe.ipfs.ipfs.twdragon.net/?now=1692736124372&filename=1x1.png

2023-08-23 10:02 UTC, twdragon commented
> https://bafybeibwzifw52ttrkqlikfzext5akxu7lz4xiwjgwzmqcpdzmp3n5vnbe.ipfs.ipfs.twdragon.net/?now=1692736124372&filename=1x1.png -> `net::ERR_CERT_COMMON_NAME_INVALID`

@SgtPooki Sorry, I forgot about the automatically added `ipfs.` prefix, changed it now. The gateway works well, it just refuses all path-based requests. The FQDN for it should be `ipfs.twdragon.net`, but not `ipfs.ipfs.twdragon.net`

2023-08-23 10:07 UTC, twdragon commented
https://bafybeibwzifw52ttrkqlikfzext5akxu7lz4xiwjgwzmqcpdzmp3n5vnbe.ipfs.twdragon.net/?now=1692736124372&filename=1x1.png

2023-09-29 13:04 UTC, merged